<a href="https://colab.research.google.com/github/MAXICAPO1999/-HelloWorldClassSabado/blob/master/Clase_1_blank_2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python para análisis de datos


Para iniciar con python se recomienda instalar [ANACONDA](https://www.continuum.io/downloads) , en la version  3.x

---


**Nota** Despues de instalado se puede cambiar de version siguiendo los  [pasos](http://conda.pydata.org/docs/py2or3.html) , [ayuda](http://stackoverflow.com/questions/30492623/using-both-python-2-x-and-python-3-x-in-ipython-notebook)
---

## Verifiquemos que tenemos lo que necesitamos

In [5]:
#@title
# Python version
import sys
print('Python: {}'.format(sys.version))

import sklearn
print('sklearn: {}'.format(sklearn.__version__))
# scipy
import scipy
print('scipy: {}'.format(scipy.__version__))
# numpy
import numpy
print('numpy: {}'.format(numpy.__version__))
# matplotlib
import matplotlib
print('matplotlib: {}'.format(matplotlib.__version__))
# pandas
import pandas
print('pandas: {}'.format(pandas.__version__))
# scikit-learn
import sklearn
print('sklearn: {}'.format(sklearn.__version__))

Python: 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)]
sklearn: 0.22
scipy: 1.3.2
numpy: 1.17.4
matplotlib: 3.1.1
pandas: 0.25.3
sklearn: 0.22


## Buscar ayuda
Tenemos la opción de usar ? para ver la ayuda de una función, o usar tab para ver las funciones disponibles de un objeto

Ejercicio: importar la biblioteca random y buscar ayuda sobre la función `random`

In [8]:
import random

random?

# Python
Python es un lenguaje de programación de alto nivel, interpretado, interactivo, orientado a objetos y de propósito general. Fue creado por Guido van Rossum durante 1985-1990. Al igual que Perl, el código fuente de Python también está disponible bajo la Licencia Pública General de GNU (GPL).

basado en [Complete Python Bootcamp: Go from zero to hero in Python 3](https://www.udemy.com/complete-python-bootcamp/) y [Python - Tutorial](https://www.tutorialspoint.com/python/index.htm) (*warning: is python2*)

- se considera la mejor práctica ([PEP8](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names)) que los nombres de las variables están en minúsculas con guiones bajos
- Python utiliza *escritura dinámica*, lo que significa que puede reasignar variables a diferentes tipos de datos.
- Python soporta cuatro tipos numéricos diferentes

  - int (enteros con signo) `5`
  - long (enteros largos, también se pueden representar en octal y hexadecimal) `5L`,` 0x80`
  - float (valores reales de punto flotante) `0.0`,` 0.5e52`
  - complejo (números complejos) `14.5j`
- Se puede pensar en las listas de la versión más general de una secuencia en Python. A diferencia de las cadenas, son mutables, lo que significa que los elementos dentro de una lista se pueden cambiar.
- Lo importante de una lista es que los elementos de una lista no tienen que ser del mismo tipo.
- Una gran característica de las estructuras de datos de Python es que admiten el anidamiento. Esto significa que podemos tener estructuras de datos dentro de estructuras de datos
-En las estructuras de datos Diccionario([dict](https://docs.python.org/3/tutorial/datastructures.html)) Las claves son únicas dentro de un diccionario, mientras que los valores pueden no serlo.
- Los valores de un diccionario pueden ser de cualquier tipo, pero las claves deben ser de un tipo de datos inmutables como cadenas, números o tuplas.
- En Python, la TUPLA es otro tipo de arreglo que dispone el Python. Esta variable está más cerca al concepto matemático de vector, puesto que en Python la tupla se maneja como una lista más cerrada porque no puede cambiar elementos individuales, en otras palabras, es inmutable según lo definen [tuples](https://docs.python.org/3/tutorial/datastructures.html#tuples-and-sequences)


## Python basico


Sin ejecutar el codigo, que crees que retorna cada item? pruebalo

1. **numbers** 

```
3/2 -> 1.5
3/float(2) -> 1.5 
3%2 -> 1
3.00//2.00 -> 1.0
2**3 -> 8
4**0.5 -> 2.0
import math
math.sqrt(4) -> 2.0
2 + 10 * 10 + 3 -> 105
(2+10) * (10+3) -> 156
```
2. **Variables**

```
a = 10
a =a + 10
a += 10
b = c = a
a,b,c = 1,2,"john"
my_dogs = 2
my_dogs = ['Sammy', 'Frankie']
del my_dogs

```
3. **string**

```
str = 'Hello World!'

print (str)     -> Hello World!     
print (str[0])       -> H
print (str[2:5])     -> llo
print (str[2:])      -> llo World!
print (str * 2)      -> Hello World!Hello World!
print (str + "TEST") -> Hello World!TEST
str.upper()
str.split()
'Carlos: {}'.format(str)
print(" %s ,  %s" %(str,"I'm Carlos")) -> Hello World! ,  I'm Carlos

print('I wrote %s programs today.' %3.75) -> I wrote 3.75 programs today.
print('I wrote %d programs today.' %3.75) -> I wrote 3 programs today.
print('I wrote %5.2f programs today.' %3.75) -> I wrote  3.75 programs today.
print('First: %s, Second: %5.2f, Third: %r' %('hi!',3.1415,'bye!')) -> First: hi!, Second:  3.14, Third: 'bye!'
print('The {2} {1} {0}'.format('fox','brown','quick')) -> The quick brown fox
print('First Object: {a}, Second Object: {b}, Third Object: {c}'.format(a=1,b='Two',c=12.3)) -> First Object: 1, Second Object: Two, Third Object: 12.3

print('{0:8} | {1:9}'.format('Fruit', 'Quantity')) -> Fruit|Quantity 
print('{0:8} | {1:9}'.format('Apples', 3.))        -> Apples|3.0
print('{0:8} | {1:9}'.format('Oranges', 10))       -> Oranges|10

```

4. **Array list**

```
my_list = [1,2,3]
my_list = ['A string',23,100.232,0]
my_list + ['new item']
my_list = my_list +['new item']
my_list.pop(0)
my_list.pop(-1)
my_list.reverse()
my_list.sort()
my_list * 2
my_list=[]
my_list=array()

num_list = range(1, 101)
print(num_list[49]) -> 50
type(num_list)
len(num_list)

new_list = [0, 1, 2, 3, 4, 5, 6]
new_list[2] = 2001;
new_list[2:5]
new_list[:3]
new_list[-2:]

list_1 = [1,2]
list_2 = [3, 4]
list_1=list_1+list_2
list_1.append(list_2)
[num*2 for num in list_1]

lst_1=[1,2,3]
lst_2=[4,5,6]
lst_3=[7,8,9]
matrix = [lst_1,lst_2,lst_3]
matrix[0][0]=8
print(matrix) -> [[8, 2, 3], [4, 5, 6], [7, 8, 9]]

```
4.  **Dictionary**

```
d = {'a':10, 'b':20, 'c':30}
d['a']
d['b']=40
d.clear()

print(d) -> {}

dict = {'Name': 'Zara', 'Age': 7, 'Name': 'Manni'}
dict.values()
dict.keys()
dict.items()
print(dict['Name']) Manni
dict2['Name']='Carlos'
dict.update(dict2)


locations = {'Sinan': ['Baltimore', 'MD'], 'Brandon': ['Arlington', 'VA']}
print(locations['Brandon'][1])

from numpy import random
data = {'a'+str(i) : random.randn() for i in range(7)}
print(data['a1'])
data
```

5. ** functions**

```
def calc(a, b):
    return a + b
print(calc(2,3)) -> 5
```

Para probar cualquiera de los códigos anteriores, simplemente copie el bloque de código en la celda de python a continuación.

![numpy](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/640px-NumPy_logo.svg.png)


## Numpy


NumPy es el paquete fundamental para la computación científica con Python. Contiene entre otras cosas:

- un poderoso objeto de matriz N-dimensional

-funciones sofisticadas (de transmisión)

- herramientas para integrar código C / C ++ y Fortran

- Álgebra lineal útil, transformada de Fourier y capacidades de números aleatorios


Todo Arreglo/array en Numpy es tratado como un objeto que entre sus propiedades tiene:

- ndarray.ndim –> Proporciona el número de dimensiones de nuestro array. El array identidad es un array cuadrado con una diagonal principal unitaria.
- ndarray.shape –> Devuelve la dimensión del array, es decir, una tupla de enteros indicando el tamaño del array en cada dimensión. Para una matriz de n filas y m columnas obtendremos (n,m).
- ndarray.size –> Es el número total de elementos del array.
- ndarray.dtype –> Es un objeto que describe el tipo de elementos del array.
- ndarray.itemsize –> devuelve el tamaño del array en bytes.
- ndarray.data –> El buffer contiene los elementos actuales del array.

## Creación de Arrays


- identity(n,dtype). Devuelve la matriz identidad, es decir, uma matriz cuadrada nula excepto en su diagonal principal que es unitaria. n es el número de filas (y columnas) que tendrá la matriz y dtype es el tipo de dato. Este argumento es opcional. Si no se establece, se toma por defecto como flotante.
- ones(shape,dtype). Crea un array de unos compuesto de shape elementos.
- zeros(shape, dtype). Crea un array de ceros compuesto de “shape” elementos”.
- empty(shape, dtype). Crea un array de ceros compuesto de “shape” elementos” sin entradas.
- eye(N, M, k, dtype). Crea un array bidimensional con unos en la diagonal k y ceros en el resto. Es similar a identity. Todos los argumentos son opcionales. N es el número de filas, M el de columnas y k es el índice de la diagonal. Cuando k=0 nos referimos a la diagonal principal y por tanto eye es similar a identity.
- arange([start,]stop[,step,],dtype=None). Crea un array con valores distanciados step entre el valor inicial star y el valor final stop. Si no se establece step python establecerá uno por defecto.
- linspace(start,stop,num,endpoint=True,retstep=False). Crea un array con valor inicial start, valor final stop y num elementos.
- meshgrid(x,y). Genera una matriz de coordenadas a partir de dos los arrays x, y.

## Funciones

El módulo numpy contiene todas las operaciones usuales entre arrays como las matemáticas (suma, resta, multiplicación, etc), las lógicas (and, or, xor, etc), binarias, ... 
[Operaciones Numpy](https://drive.google.com/file/d/17wZqpCvckCb8Ous3HAaRqPu33rJKtTeB/view?usp=sharing)


[buen tutorial](http://pendientedemigracion.ucm.es/info/aocg/python/modulos_cientificos/numpy/index.html)

Lo más fácil y sencillo es en caso de duda consultar la documentación oficial. [documentacion](https://docs.scipy.org/doc/numpy/reference/index.html#reference)

In [9]:
import numpy as np # Importamos numpy como el alias np

In [10]:

# tipo de datos
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
#funciones basicas
miArray = np.arange(10) # Creamos un array de 0 a 9 separados de uno en uno
print (miArray) # Presentamos en pantalla el array creado
print (type(miArray))   #Comprobamos que es un ndarray
print (miArray.ndim )   # Consultamos el número de dimensiones
print (miArray.shape )  # Consultamos la dimensión
print (miArray.size )  # Consultamos la dimensión
print (miArray.dtype )  # Consultamos el tipo de elementos del array
print (miArray.itemsize )  # tamaño en bytes
print (miArray.data )  # Consultamos el buffer de memoria.

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
1
(10,)
10
int32
4
<memory at 0x0000017EE0091AC8>

In [11]:
# array bidimensionales
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr2d[2])

print(arr2d[0][2])
#arr2d[0,2]

#grupo de elementos
print((arr2d[:,1]))

# acesso con operaciones
print(arr2d[arr2d>4])

#fancy indexing (una matrix es en verdad un arreglo)
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
print(arr)

#seleccionar columnas en desorden
print (arr[[4, 3, 0, 6]])
#Using negative indices select rows from the end
print(arr[[-3, -5, -7]])

#reorganizar vectores
arr = np.arange(32).reshape((8, 4))
print(arr)

[7 8 9]
3
[2 5 8]
[5 6 7 8 9]
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [6. 6. 6. 6.]]
[[5. 5. 5. 5.]
 [3. 3. 3. 3.]
 [1. 1. 1. 1.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

### **Ejercicio**

Crear dos vectores de diez numeros aleatorios enteros [np.random.randint](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html) entre 1 y 10 y realizar las siguientes operaciones:
- sumarlos
- concatenar los dos arreglos
- encontrar la sumatoria de los valores
- encontrar la media de los valores
- imprimir los numeros mayores que 5
- determinar las posiciones de los numeros que son iguales en los arreglos

In [251]:
arr1 = np.array(np.random.randint(1,11, size=10))
arr2 = np.array(np.random.randint(1,11, size=10))

print ("Vector 1: ",arr1)
print ("Vector 2: ",arr2)
print ("")

# Suma
print ("Suma: ",arr1+arr2)
print ("")

# Concatenacion
print("Concatenacion: ",np.concatenate((arr1, arr2)))
print ("")

# Sumatoria de los valores
print("Sumatoria de los valores vector 1: ",np.sum(arr1))
print("Sumatoria de los valores vector 2: ",np.sum(arr2))
print ("")

# Media de los valores
print("Media de los valores vector 1: ",np.mean(arr1))
print("Media de los valores vector 2: ",np.mean(arr2))
print ("")

# Imprimir los numeros mayores  5
print("Mayores que 5 en vector 1: ",arr1[arr1 > 5])
print("Mayores que 5 en vector 2: ",arr2[arr2 > 5])
print ("")

# Determinar las posiciones de los numero que son iguales en los arreglos
condicion = np.equal(arr1,arr2)
print("Posiciones donde los numeros son iguales entre los dos arreglos: \n",np.where(condicion))

Vector 1:  [8 2 8 7 7 6 5 6 3 6]
Vector 2:  [10  2  5  4 10  9  9  6  4  6]

Suma:  [18  4 13 11 17 15 14 12  7 12]

Concatenacion:  [ 8  2  8  7  7  6  5  6  3  6 10  2  5  4 10  9  9  6  4  6]

Sumatoria de los valores vector 1:  58
Sumatoria de los valores vector 2:  65

Media de los valores vector 1:  5.8
Media de los valores vector 2:  6.5

Mayores que 5 en vector 1:  [8 8 7 7 6 6 6]
Mayores que 5 en vector 2:  [10 10  9  9  6  6]

Posiciones donde los numeros son iguales entre los dos arreglos:
 (array([1, 7, 9], dtype=int64),)

## SQLite

Cuando abre un excel o CSV en Python y lo asigna a un nombre de variable, está usando la memoria de su computadora para guardar esa variable. Acceder a los datos desde una base de datos como SQL no solo es más eficiente, sino que también le permite importar solo las partes de los datos que necesita.


Cada una de las bases de datos tienen sus librerias para python, a manera de ejemplo veamos SQLite.

- Revisar la base de datos en linea [sqliteonline](https://sqliteonline.com/)


- **Ejercicio** escribamos tres query (enunciado en [Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) y luego el codigo sql respectivo.

los datos son   la Guía de valor para vehículos en Colombia suministrada por fasecolda, que se puede descargar de [Kaggle](https://www.kaggle.com/panchicore/vehicles-colombia-fasecolda/version/1)


[Link de descarga](https://drive.google.com/file/d/1wVSVbq1cJ68dU-0D8c4tPh83Hjy8azPM/view?usp=sharing)


tutorial [sqllite](http://www.datacarpentry.org/python-ecology-lesson/08-working-with-sql)

In [259]:
#Esto se elaboro desde Jupyter
# Cargamos el archivo (solo en collaborative) en caso contrario colocar el archivo en la raiz
#from google.colab import files
#files.upload()

In [269]:

import sqlite3

# Create a SQL connection to our SQLite database
con = sqlite3.connect("guia_fasecolda.sqlite")

cur = con.cursor()

# the result of a "cursor.execute" can be iterated over by row

for row in cur.execute('SELECT Marca,Referencia1,Cilindraje,Peso,"2015","2016","2017" FROM carros where Cilindraje<1500 AND Cilindraje>1200 AND "2015">0;'):
   print(row)
    

#AQUI Realize sus consultas sql de los datos

#1, Query para traer la marca de carro AUDI y la clase a la cual pertenece y del año del 2018 o mas actual
print("Query para traer la marca de carro AUDI y la clase a la cual pertenece y del año del 2018 o mas actual")
print()
for row in cur.execute('SELECT Marca,Clase FROM carros where Marca = "AUDI" AND "2018">0 order by clase;'):
   print(row)
print("Query para traer cantidad de carros importados segun su marca")
print()

#2, Query para traer cantidad de carros importados segun su marca
for row in cur.execute('SELECT count(*),Marca FROM carros where Importado > 0 group by Marca;'):
   print(row)
  
print("Query para traer la marca de vehiculos que pesan mas de 1000 y que servicio prestan")
print()
#3, Query para traer la marca de vehiculos que pesan mas de 1000 y que servicio prestan
for row in cur.execute('SELECT distinct Marca, Servicio FROM carros where peso >= 1000;'):
   print(row)
    

#Be sure to close the connection.
con.close()

('AUDI', 'A1', 1390, 1200, 72900, 0, 0)
('AUDI', 'A1 SPORTBACK', 1390, 1225, 74900, 0, 0)
('AUDI', 'Q3', 1395, 1480, 85700, 0, 0)
('BMW', '218I', 1499, 1435, 83800, 89900, 101100)
('CHEVROLET', 'SAIL', 1398, 1070, 25800, 27800, 29800)
('CHEVROLET', 'SAIL', 1398, 1070, 27300, 29500, 32000)
('CHEVROLET', 'SAIL', 1398, 1070, 30300, 33200, 36000)
('CHEVROLET', 'SAIL', 1398, 1070, 31500, 34400, 38800)
('CHEVROLET', 'SAIL', 1398, 1060, 28400, 31800, 0)
('CHEVROLET', 'SAIL', 1399, 1082, 29200, 0, 0)
('CHEVROLET', 'SPARK [3] [FL]', 1206, 979, 28800, 30700, 32800)
('CHEVROLET', 'SPARK [3] [FL]', 1206, 965, 26100, 27800, 29700)
('CHEVROLET', 'SAIL', 1399, 1090, 30200, 33000, 39700)
('CHEVROLET', 'SAIL', 1398, 1092, 25400, 27400, 29100)
('CHEVROLET', 'SAIL', 1398, 1092, 26900, 29000, 31300)
('CHEVROLET', 'VAN N300', 1206, 1125, 34400, 38000, 41500)
('CHEVROLET', 'VAN N300', 1206, 1125, 35500, 0, 0)
('CHEVROLET', 'VAN N300', 1206, 1180, 38000, 42000, 45900)
('CHEVROLET', 'VAN N300', 1206, 1125, 32200, 36500, 44500)
('CHEVROLET', 'VAN N300', 1206, 1125, 33900, 38800, 46900)
('CHEVROLET', 'N300', 1485, 1105, 34500, 43200, 48500)
('CHEVROLET', 'N300', 1485, 1105, 30800, 38600, 45200)
('DAIHATSU', 'TERIOS', 1495, 1160, 52900, 56800, 0)
('DAIHATSU', 'TERIOS', 1495, 1160, 55000, 59200, 0)
('DAIHATSU', 'TERIOS', 1495, 1160, 47000, 50500, 0)
('DAIHATSU', 'TERIOS', 1495, 1160, 46000, 0, 0)
('DUCATI', 'SUPERBIKE', 1285, 166, 85000, 95900, 0)
('FIAT', '500', 1368, 1118, 37000, 40000, 0)
('FIAT', 'UNO', 1368, 940, 32400, 34800, 0)
('FIAT', '500', 1368, 1080, 34300, 0, 0)
('FIAT', '500', 1368, 1153, 38600, 41200, 0)
('FIAT', '500', 1368, 1153, 44200, 0, 0)
('FIAT', '500', 1368, 1153, 50500, 0, 0)
('FIAT', 'PALIO [5]', 1368, 1048, 30000, 0, 0)
('FIAT', '500', 1368, 0, 62700, 0, 0)
('FIAT', 'UNO', 1368, 0, 27100, 30000, 0)
('FIAT', 'FIORINO [3]', 1368, 650, 31000, 33200, 38400)
('FIAT', 'FIORINO [3]', 1368, 650, 29000, 31100, 0)
('FIAT', 'STRADA [4]', 1368, 1051, 32000, 0, 0)
('FIAT', 'STRADA [4][FL]', 1368, 1106, 36300, 40000, 0)
('HYUNDAI', 'ACCENT i25', 1396, 1035, 35600, 37100, 0)
('HYUNDAI', 'ACCENT i25', 1396, 1035, 34500, 36000, 0)
('HYUNDAI', 'ACCENT VERNA [FL]', 1495, 960, 31100, 34200, 0)
('HYUNDAI', 'GRAND I10', 1248, 1000, 30800, 33100, 0)
('HYUNDAI', 'GRAND I10', 1248, 1027, 35000, 37500, 0)
('HYUNDAI', 'GRAND I10', 1248, 1018, 28900, 38900, 41300)
('HYUNDAI', 'GRAND I10', 1248, 1430, 36000, 38600, 0)
('HARLEY DAVIDSON', 'SPORTSTER', 1202, 247, 41000, 49900, 0)
('HARLEY DAVIDSON', 'NIGHT ROD SPECIAL', 1250, 304, 59100, 0, 0)
('HONDA', 'FIT [3]', 1498, 1193, 50000, 63000, 69000)
('HONDA', 'FIT [3]', 1498, 1140, 45500, 54000, 0)
('HONDA', 'FIT [3]', 1498, 1140, 50100, 60000, 0)
('HONDA', 'VFR [1]', 1237, 275, 47000, 0, 0)
('KIA', 'PICANTO ION XTREM', 1248, 845, 25000, 0, 0)
('KIA', 'PICANTO ION XTREM', 1248, 845, 26200, 0, 0)
('KIA', 'PICANTO ION XTREM', 1248, 875, 31600, 0, 0)
('KIA', 'EKOTAXI +', 1248, 845, 29600, 0, 0)
('KIA', 'EKOTAXI +', 1248, 845, 32000, 0, 0)
('KIA', 'RIO SPICE', 1248, 0, 36000, 0, 0)
('KIA', 'RIO SPICE', 1248, 0, 36000, 0, 0)
('KIA', 'RIO SPICE', 1396, 0, 46000, 0, 0)
('KIA', 'RIO SPICE', 1248, 0, 35100, 0, 0)
('KIA', 'RIO SPICE', 1396, 0, 46000, 0, 0)
('KIA', 'RIO SPICE', 1396, 0, 39000, 0, 0)
('KIA', 'RIO SPICE', 1396, 0, 45000, 0, 0)
('KIA', 'RIO SPICE', 1396, 0, 43000, 0, 0)
('KIA', 'RIO SPICE', 1248, 0, 36200, 0, 0)
('KIA', 'RIO SPICE', 1396, 0, 42200, 0, 0)
('KIA', 'RIO SPICE', 1396, 0, 43500, 0, 0)
('KIA', 'PICANTO ION XTREM [FL]', 1248, 845, 26400, 29100, 0)
('KIA', 'PICANTO ION XTREM [FL]', 1248, 845, 25200, 0, 0)
('KIA', 'PICANTO ION XTREM [FL]', 1248, 0, 31000, 0, 0)
('KIA', 'PICANTO ION XTREM [FL]', 1248, 0, 31800, 0, 0)
('KIA', 'RIO SPICE R', 1248, 0, 40000, 44200, 50100)
('KIA', 'RIO R', 1396, 0, 43500, 47100, 53700)
('KIA', 'RIO SPICE R', 1396, 0, 44200, 47900, 54300)
('KIA', 'RIO R', 1248, 0, 35000, 40700, 46500)
('MAZDA', '2 [1] [FL]', 1498, 1020, 37700, 0, 0)
('MAZDA', '2 [1] [FL]', 1498, 1020, 37400, 0, 0)
('MINI', 'COOPER', 1499, 1115, 77900, 83900, 98900)
('MINI', 'COOPER', 1499, 1085, 68900, 69900, 79900)
('MINI', 'COOPER', 1499, 1115, 70900, 71900, 84900)
('MINI', 'COOPER', 1499, 0, 73900, 89700, 101900)
('MINI', 'COOPER', 1499, 1220, 67100, 72900, 82900)
('MG', '3', 1498, 0, 31800, 35000, 0)
('MG', '3', 1498, 0, 34100, 37600, 0)
('MG', '5', 1498, 0, 41500, 0, 0)
('MG', '3', 1498, 0, 33100, 36500, 0)
('MG', '3', 1498, 0, 30000, 33100, 0)
('MG', '350', 1498, 0, 42300, 0, 0)
('RENAULT', 'LOGAN F.II', 1390, 975, 22600, 24200, 0)
('RENAULT', 'LOGAN F.II', 1390, 975, 24400, 26200, 0)
('SEAT', 'IBIZA [5]', 1390, 1130, 47500, 0, 0)
('SKODA', 'OCTAVIA [3]', 1395, 1265, 64700, 71900, 79900)
('SUZUKI', 'SWIFT [3]', 1372, 1005, 38600, 42800, 51500)
('SUZUKI', 'SWIFT [3]', 1372, 1035, 39900, 44300, 56500)
('SUZUKI', 'CIAZ', 1373, 1020, 39000, 45100, 54500)
('SUZUKI', 'CIAZ', 1373, 1020, 41900, 48500, 58500)
('SUZUKI', 'CIAZ', 1373, 1010, 35200, 40800, 49500)
('SUZUKI', 'CIAZ', 1373, 1010, 38100, 44200, 53500)
('SUZUKI', 'ERTIGA', 1373, 1160, 42700, 45800, 50000)
('SUZUKI', 'ERTIGA', 1373, 1185, 45500, 48800, 53600)
('SUZUKI', 'JIMNY', 1328, 1060, 38700, 42300, 55600)
('CHERY', 'NICE', 1297, 1040, 22100, 0, 0)
('CHERY', 'YOYA', 1297, 0, 33200, 0, 0)
('CHERY', 'YOYA', 1497, 0, 35000, 39000, 43000)
('CHERY', 'X-CROSS', 1497, 1200, 30400, 39500, 0)
('CHERY', 'YOYA', 1497, 0, 33900, 36200, 0)
('CHERY', 'YOYA', 1297, 0, 29400, 0, 0)
('CHERY', 'YOYA', 1497, 1295, 32700, 35100, 37700)
('HAFEI', 'JUNYI', 1299, 1095, 29900, 0, 0)
('HAFEI', 'JUNYI', 1299, 1095, 29900, 0, 0)
('HAFEI', 'JUNYI', 1299, 1095, 27400, 0, 0)
('CHANGHE', 'FREEDOM [2]', 1243, 1085, 35100, 37700, 0)
('CHANGHE', 'FREEDOM [2]', 1243, 1085, 36100, 38700, 0)
('CHANGHE', 'FREEDOM [2]', 1243, 1085, 28900, 34400, 0)
('CHANGHE', 'FREEDOM [2]', 1372, 955, 32800, 35200, 38300)
('CHANGHE', 'FREEDOM [2]', 1372, 955, 27000, 0, 0)
('CHANGHE', 'FREEDOM [2]', 1372, 955, 30700, 33900, 37500)
('CHANGHE', 'FREEDOM [2]', 1372, 905, 29000, 32000, 38000)
('BYD', 'F3', 1488, 1200, 26000, 0, 0)
('BYD', 'F3', 1488, 1200, 30900, 0, 0)
('BYD', 'F3 [2]', 1497, 0, 29800, 0, 0)
('BYD', 'QIN', 1497, 1720, 89000, 0, 0)
('JAC', 'STAR', 1332, 1100, 26600, 0, 0)
('JAC', 'STAR', 1332, 1100, 25100, 0, 0)
('JAC', 'VELOCE', 1332, 1475, 26700, 0, 0)
('JAC', 'STAR', 1332, 1475, 21300, 0, 0)
('JAC', 'VELOCE', 1332, 1475, 19100, 0, 0)
('JAC', 'SMILE', 1332, 915, 24000, 0, 0)
('JAC', 'VELOCE', 1332, 1435, 21400, 24000, 0)
('JAC', 'B-CROSS', 1499, 1424, 31400, 0, 0)
('DFSK/DFM/DFZL', 'VAN PASAJEROS', 1310, 1030, 27900, 0, 42900)
('DFSK/DFM/DFZL', 'VAN PASAJEROS LW', 1310, 1030, 30400, 0, 0)
('DFSK/DFM/DFZL', 'V27', 1298, 1100, 27500, 30100, 0)
('DFSK/DFM/DFZL', 'V29', 1298, 1125, 33600, 0, 0)
('DFSK/DFM/DFZL', 'MINIVAN', 1298, 1200, 26500, 0, 0)
('DFSK/DFM/DFZL', 'C37', 1375, 1275, 34000, 37600, 49900)
('DFSK/DFM/DFZL', 'JOYEAR', 1499, 1250, 33100, 0, 0)
('DFSK/DFM/DFZL', 'JOYEAR', 1499, 1250, 35000, 38000, 0)
('DFSK/DFM/DFZL', 'GLORY', 1299, 1235, 37000, 42500, 47900)
('DFSK/DFM/DFZL', 'C37', 1375, 1290, 38400, 44000, 51500)
('DFSK/DFM/DFZL', 'VAN CARGA', 1310, 1005, 25000, 28000, 38400)
('DFSK/DFM/DFZL', 'V25', 1298, 1070, 31000, 34000, 0)
('DFSK/DFM/DFZL', 'C35', 1375, 0, 34000, 38000, 46900)
('DFSK/DFM/DFZL', 'MINIVAN', 1298, 0, 25500, 0, 0)
('DFSK/DFM/DFZL', 'EQ1020TF T03', 1300, 1000, 25500, 32000, 38900)
('DFSK/DFM/DFZL', 'EQ1020TF T03', 1300, 0, 29500, 35000, 42900)
('DFSK/DFM/DFZL', 'V21', 1298, 970, 34800, 42100, 0)
('DFSK/DFM/DFZL', 'EQ1021GF 24Q', 1310, 760, 26600, 0, 0)
('DFSK/DFM/DFZL', 'PICK UP', 1310, 915, 25700, 28900, 35400)
('DFSK/DFM/DFZL', 'DFA', 1310, 915, 25500, 28900, 36900)
('DFSK/DFM/DFZL', 'V21', 1298, 970, 28500, 32400, 0)
('DFSK/DFM/DFZL', 'PICK UP', 1310, 0, 27500, 0, 0)
('DFSK/DFM/DFZL', 'V22', 1298, 1100, 32000, 37000, 44000)
('BRP CAN AM', 'SPYDER', 1330, 0, 85000, 0, 0)
('GREAT WALL MOTOR', 'VOOLEX', 1497, 1125, 32000, 35000, 0)
('GREAT WALL MOTOR', 'VOOLEX', 1497, 0, 37700, 41000, 0)
('KTM', '1290', 1301, 229, 61600, 68400, 76000)
('ZOTYE', 'DUNA', 1298, 1130, 28900, 0, 0)
('ZOTYE', 'ZONORA', 1299, 0, 32800, 0, 0)
('LIFAN', 'FOISON', 1342, 1130, 33000, 0, 0)
('LIFAN', 'SEASION', 1342, 1205, 35300, 0, 0)
('LIFAN', 'FOISON', 1342, 1100, 29000, 0, 0)
('LIFAN', 'DURA TRUCK', 1342, 1000, 27500, 35900, 0)
('LIFAN', 'DURA TRUCK', 1342, 1134, 32500, 39600, 0)
('FAW AMI', 'V5', 1495, 995, 25100, 29300, 39500)
('FAW AMI', 'CA6390B5', 1339, 1123, 29800, 0, 0)
('FAW AMI', 'CA6390B5', 1339, 1123, 28300, 0, 0)
('ALFA ROMEO', 'MiTo', 1368, 1145, 67200, 0, 0)
('ALFA ROMEO', 'MiTo', 1368, 1145, 76300, 0, 0)
('ALFA ROMEO', 'MiTo', 1368, 1135, 71100, 0, 0)
('ALFA ROMEO', 'GIULIETTA', 1368, 1310, 74500, 0, 0)
('TRIUMPH', 'TIGER', 1215, 0, 53600, 57500, 0)
('BRILLIANCE', 'H220', 1498, 1207, 26000, 35500, 0)
('BRILLIANCE', 'V5', 1498, 1785, 42100, 0, 0)
('BRILLIANCE', 'V5', 1498, 1785, 45000, 50000, 0)
('BAIC', 'A115', 1499, 1090, 40500, 0, 0)
('BAIC', 'A115', 1499, 1105, 39500, 0, 0)
('BAIC', 'BJ206S8', 1342, 1085, 28600, 0, 0)
('BAIC', 'BJ206C', 1342, 1020, 26400, 34000, 0)
('BAIC', 'T205-D', 1342, 1050, 26500, 37000, 0)
('BAIC', 'T205-D', 1342, 1050, 23800, 0, 0)
('BAIC', 'T205-D', 1342, 1050, 25700, 0, 0)
('CHANGAN', 'CX20', 1370, 1060, 31500, 38500, 0)
('CHANGAN', 'MINI VAN', 1243, 1130, 28500, 32500, 36500)
('CHANGAN', 'MINI VAN', 1243, 1130, 26500, 30400, 32600)
('CHANGAN', 'MINI TRUK', 1243, 970, 35400, 0, 0)
('CHANGAN', 'MINI TRUCK', 1243, 1070, 21800, 0, 31200)
('CHANGAN', 'MINI TRUCK', 1243, 1070, 22800, 25000, 0)
('CHANGAN', 'MINI TRUCK', 1243, 970, 25000, 26100, 34000)
Query para traer la marca de carro AUDI y la clase a la cual pertenece y del año del 2018 o mas actual
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'AUTOMOVIL')
('AUDI', 'CAMIONETA PASAJ.')
('AUDI', 'CAMIONETA PASAJ.')
('AUDI', 'CAMIONETA PASAJ.')
('AUDI', 'CAMIONETA PASAJ.')
('AUDI', 'CAMIONETA PASAJ.')
('AUDI', 'CAMIONETA PASAJ.')
('AUDI', 'CAMIONETA PASAJ.')
('AUDI', 'CAMIONETA PASAJ.')
('AUDI', 'CAMIONETA PASAJ.')
('AUDI', 'CAMIONETA PASAJ.')
('AUDI', 'CAMIONETA PASAJ.')
('AUDI', 'CAMIONETA PASAJ.')
('AUDI', 'CAMIONETA PASAJ.')
('AUDI', 'CAMIONETA PASAJ.')
('AUDI', 'CAMIONETA PASAJ.')
('AUDI', 'CAMIONETA PASAJ.')
('AUDI', 'CAMIONETA PASAJ.')
('AUDI', 'CAMIONETA PASAJ.')
('AUDI', 'CAMIONETA PASAJ.')
('AUDI', 'CAMIONETA PASAJ.')
('AUDI', 'CAMIONETA PASAJ.')
('AUDI', 'CAMIONETA PASAJ.')
('AUDI', 'CAMIONETA PASAJ.')
('AUDI', 'CAMIONETA PASAJ.')
('AUDI', 'CAMIONETA PASAJ.')
('AUDI', 'CAMIONETA PASAJ.')
('AUDI', 'CAMIONETA PASAJ.')
('AUDI', 'CAMIONETA PASAJ.')
('AUDI', 'CAMIONETA PASAJ.')
('AUDI', 'CAMIONETA PASAJ.')
('AUDI', 'CAMIONETA PASAJ.')
('AUDI', 'CAMIONETA PASAJ.')
('AUDI', 'CAMIONETA PASAJ.')
('AUDI', 'CAMPERO')
('AUDI', 'CAMPERO')
('AUDI', 'CAMPERO')
('AUDI', 'CAMPERO')
('AUDI', 'CAMPERO')
('AUDI', 'CAMPERO')
('AUDI', 'CAMPERO')
('AUDI', 'CAMPERO')
('AUDI', 'CAMPERO')
('AUDI', 'CAMPERO')
('AUDI', 'CAMPERO')
('AUDI', 'CAMPERO')
('AUDI', 'CAMPERO')
('AUDI', 'CAMPERO')
Query para traer cantidad de carros importados segun su marca
(5, 'ACB')
(6, 'ACURA')
(5, 'AG')
(35, 'AGRALE')
(18, 'AKT')
(1, 'ALEKO')
(9, 'ALFA ROMEO')
(6, 'AMC')
(3, 'AMERICAN MOTOR')
(25, 'AMPLE')
(24, 'APRILIA')
(3, 'ARCTIC CAT')
(6, 'AROCARPATI')
(11, 'ASIA')
(2, 'ATM')
(226, 'AUDI')
(8, 'AUPACO')
(40, 'AUTECO')
(1, 'AUTOCAR')
(1, 'AVA')
(17, 'AYCO')
(16, 'BAIC')
(4, 'BAW')
(4, 'BEIJING')
(6, 'BENELLI')
(481, 'BMW')
(1, 'BORGO')
(8, 'BRILLIANCE')
(2, 'BRONTO')
(32, 'BRP CAN AM')
(10, 'BUICK')
(19, 'BYD')
(11, 'CADILLAC')
(9, 'CAGIVA')
(1, 'CARMEX')
(38, 'CHANA')
(15, 'CHANGAN')
(3, 'CHANGFENG')
(28, 'CHANGHE')
(36, 'CHERY')
(319, 'CHEVROLET')
(22, 'CHRYSLER')
(4, 'CIMC')
(128, 'CITROEN')
(9, 'CMC')
(3, 'CORCEL')
(9, 'DACIA')
(1, 'DADI')
(73, 'DAEWOO')
(2, 'DAF')
(89, 'DAIHATSU')
(4, 'DAYANG')
(2, 'DERBI')
(52, 'DFAC')
(121, 'DFSK/DFM/DFZL')
(18, 'DINA')
(117, 'DODGE')
(1, 'DONGBEN')
(1, 'DS')
(71, 'DUCATI')
(1, 'DUST')
(3, 'EAGLE CARGO')
(4, 'EUROPAMOTOS')
(1, 'EUROSTAR D`LONG')
(41, 'FAW AMI')
(3, 'FERRARI')
(136, 'FIAT')
(7, 'FIRENZE')
(1, 'FONTAINE')
(389, 'FORD')
(197, 'FOTON')
(53, 'FREIGHTLINER')
(23, 'FUSO')
(2, 'GAS GAS')
(19, 'GAZ')
(13, 'GEELY')
(3, 'GLOW')
(11, 'GMC')
(18, 'GOLDEN DRAGON')
(7, 'GOMOTOR')
(10, 'GONOW')
(4, 'GREAT DANE')
(66, 'GREAT WALL MOTOR')
(7, 'GUZI')
(48, 'HAFEI')
(13, 'HAIMA')
(6, 'HALEI')
(2, 'HAOJIANG')
(2, 'HAOJUE')
(79, 'HARLEY DAVIDSON')
(1, 'HEIL')
(9, 'HERO')
(8, 'HIGER')
(86, 'HINO')
(296, 'HONDA')
(1, 'HONGXING')
(10, 'HONLEI')
(4, 'HUALIN')
(1, 'HUANGHAI')
(7, 'HUMMER')
(4, 'HUSQVARNA')
(5, 'HYOSUNG')
(494, 'HYUNDAI')
(3, 'IFA')
(3, 'INFINITI')
(199, 'INTERNATIONAL')
(10, 'ISUZU')
(78, 'IVECO')
(200, 'JAC')
(26, 'JAGUAR')
(1, 'JAWA')
(131, 'JEEP')
(18, 'JIALING')
(27, 'JINBEI')
(20, 'JINCHENG')
(4, 'JINFENG')
(1, 'JINGLONG')
(87, 'JMC')
(4, 'JOYLONG')
(10, 'KAMAZ')
(78, 'KAWASAKI')
(9, 'KAYAK')
(11, 'KAZUKI')
(20, 'KEEWAY')
(61, 'KENWORTH')
(444, 'KIA')
(8, 'KRAZ')
(58, 'KTM')
(23, 'KYMCO')
(5, 'KYOTO')
(17, 'LADA')
(7, 'LANCIA')
(113, 'LAND ROVER')
(3, 'LANDWIND')
(28, 'LEXUS')
(30, 'LIFAN')
(3, 'LINCOLN')
(1, 'LML')
(1, 'LMX')
(1, 'LOHR')
(51, 'MACK')
(18, 'MAHINDRA')
(5, 'MARMON')
(10, 'MASERATI')
(1, 'MAXMOTOR')
(3, 'MAXUS')
(109, 'MAZDA')
(4, 'MD BIKES')
(505, 'MERCEDES BENZ')
(6, 'MERCURY')
(31, 'MG')
(64, 'MINI')
(259, 'MITSUBISHI')
(1, 'MORINI')
(8, 'MOTO ABC')
(6, 'MOTO GUZZI')
(2, 'MTK')
(3, 'MUDAN')
(10, 'MV AGUSTA')
(487, 'NISSAN')
(4, 'NITRO')
(4, 'NON PLUS ULTRA')
(2, 'OLTCIT')
(3, 'OPEL')
(2, 'PASSAGGIO')
(1, 'PAZ')
(3, 'PEGASO')
(2, 'PETERBILT')
(212, 'PEUGEOT')
(29, 'PIAGGIO')
(2, 'PIONEER')
(11, 'POLARIS')
(6, 'PONTIAC')
(99, 'PORSCHE')
(13, 'QINGQI')
(3, 'RANDON')
(179, 'RENAULT')
(1, 'RENNO')
(7, 'ROVER')
(12, 'ROYAL ENFIELD')
(1, 'SAAB')
(10, 'SACHS')
(13, 'SAICWULING')
(1, 'SANYA')
(2, 'SATURN')
(36, 'SCANIA')
(2, 'SCION')
(1, 'SCOMADI')
(87, 'SEAT')
(8, 'SHINERAY')
(2, 'SHUANGHUAN')
(22, 'SIGMA')
(13, 'SINOTRUK')
(1, 'SISU')
(122, 'SKODA')
(9, 'SKYGO')
(1, 'SMART')
(2, 'SMC')
(1, 'SOYAT')
(89, 'SSANGYONG')
(1, 'STEYR')
(4, 'STÄRKER')
(132, 'SUBARU')
(6, 'SUKIDA')
(1, 'SUKYAMA')
(157, 'SUZUKI')
(10, 'SYM')
(7, 'T-KING')
(10, 'TATA')
(1, 'TAVRIA')
(1, 'TEMPEST')
(1, 'TIANMA')
(18, 'TITANIA')
(4, 'TMD')
(15, 'TONGKO')
(358, 'TOYOTA')
(29, 'TRIUMPH')
(11, 'TVS')
(1, 'TX MOTORS')
(7, 'UAZ')
(1, 'UFO')
(2, 'UKM')
(52, 'UNITED MOTORS')
(8, 'USW MOTORS')
(6, 'UTILITY')
(1, 'VAISAND')
(3, 'VENTO')
(9, 'VERUCCI')
(19, 'VESPA')
(1, 'VOLGA')
(493, 'VOLKSWAGEN')
(184, 'VOLVO')
(1, 'WABASH NATIONAL')
(1, 'WANXIN')
(14, 'WCR')
(2, 'WESTERN STAR')
(1, 'XIANFENG')
(2, 'XINGYUE')
(5, 'XINKAI')
(9, 'YAKIMA')
(128, 'YAMAHA')
(3, 'YAXING')
(1, 'YINGANG')
(18, 'YUEJIN-NAVECO')
(1, 'YUGO')
(9, 'YUTONG')
(4, 'ZAHAV')
(1, 'ZHONGNENG')
(13, 'ZHONGXING')
(6, 'ZNA')
(6, 'ZONGSHEN')
(6, 'ZOTYE')
(7, 'ZQ MOTORS')
Query para traer la marca de vehiculos que pesan mas de 1000 y que servicio prestan
('ALEKO', 'Publico')
('AMERICAN MOTOR', 'Particular')
('AROCARPATI', 'Particular')
('AROCARPATI', 'Publico')
('ASIA', 'Particular')
('AUDI', 'Particular')
('BMW', 'Particular')
('DINA', 'Particular')
('DINA', 'Publico')
('BUICK', 'Particular')
('CADILLAC', 'Particular')
('CORCEL', 'Particular')
('CHEVROLET', 'Particular')
('CHEVROLET', 'Publico')
('CHRYSLER', 'Particular')
('CITROEN', 'Particular')
('CITROEN', 'Publico')
('DACIA', 'Publico')
('DACIA', 'Particular')
('DAEWOO', 'Particular')
('DAEWOO', 'Publico')
('DAIHATSU', 'Particular')
('DAIHATSU', 'Publico')
('DODGE', 'Particular')
('DODGE', 'Publico')
('FIAT', 'Particular')
('FIAT', 'Publico')
('FREIGHTLINER', 'Publico')
('FREIGHTLINER', 'Particular')
('FORD', 'Particular')
('FORD', 'Publico')
('HYUNDAI', 'Particular')
('HYUNDAI', 'Publico')
('HONDA', 'Particular')
('IFA', 'Particular')
('INTERNATIONAL', 'Publico')
('INTERNATIONAL', 'Particular')
('HINO', 'Particular')
('HINO', 'Publico')
('ISUZU', 'Particular')
('JAGUAR', 'Particular')
('JEEP', 'Particular')
('KAMAZ', 'Publico')
('KENWORTH', 'Particular')
('KENWORTH', 'Publico')
('KIA', 'Particular')
('KIA', 'Publico')
('KRAZ', 'Particular')
('LADA', 'Particular')

## Pandas

![Panda Logo](https://pandas.pydata.org/_static/pandas_logo.png)

Documentación de [Pandas](http://pandas.pydata.org/pandas-docs/stable/10min.html)

Pandas es una librería para el análisis de datos que cuenta con las estructuras de datos que necesitamos para limpiar los datos en bruto y que sean aptos para el análisis (por ejemplo, tablas). Es importante señalar aquí que, dado que pandas lleva a cabo tareas importantes, como alinear datos para su comparación, fusionar conjuntos de datos, gestión de datos perdidos, etc., se ha convertido en una librería muy importante para procesar datos a alto nivel en Python (es decir, estadísticas ). Pandas fue diseñada originalmente para gestionar datos financieros, y como alternativa al uso de hojas de cálculo (es decir, Microsoft Excel). Esta libreria tambien es equivalente en gran parte a las estructuras de datos de R.

La estructura de datos básica de pandas son:

- **Series**: Son arrays unidimensionales con indexación (arrays con índice o etiquetados), similar a los diccionarios. Pueden generarse a partir de diccionarios o de listas.
- **DataFrame**: Es una colección ordenada de columnas con nombres y tipos. Son estructuras de datos similares a las tablas de bases de datos relacionales como SQL, donde una sola fila representa un único caso (ejemplo) y las columnas representan atributos particulares. 
- **Panel, Panel4D y PanelND**: Estas estructuras de datos permiten trabajar con más de dos dimensiones. 

Sobre este tipo de estructura de datos se aplican funciones, ejemplo:

In [272]:
import pandas as pd

dates = pd.date_range('20200101', periods=6)
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))

In [271]:
#valores iniciales de la lista
df.head()

                   A         B         C         D
2020-01-01 -0.557233  0.045897  1.420736  0.573151
2020-01-02  2.070520 -1.870783  2.033742 -0.336818
2020-01-03 -1.080506 -1.805976  0.160934  1.283238
2020-01-04  1.747286  0.537483 -0.453318 -1.392077
2020-01-05  0.019091 -0.200077  1.796810  3.231168

In [273]:
#valores finales de la lista
df.tail(3)

                   A         B         C         D
2020-01-04  0.714861 -0.995821  0.685179 -0.740736
2020-01-05 -0.952262  0.024284  0.211191 -2.044439
2020-01-06 -1.416184  2.655554 -1.022934  0.386535

In [274]:
#aceder a los datos como un arreglo numpy
print(df.index)
print(df.columns)
df.values

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06'],
              dtype='datetime64[ns]', freq='D')
Index(['A', 'B', 'C', 'D'], dtype='object')

array([[ 0.79711119,  0.40561474, -0.98769696,  0.56986415],
       [-0.47073051, -0.2084578 ,  1.89530398,  1.03672587],
       [ 1.15460053, -0.29843778, -0.5226866 ,  1.40181136],
       [ 0.71486101, -0.99582058,  0.68517904, -0.74073595],
       [-0.95226232,  0.02428391,  0.21119073, -2.04443913],
       [-1.4161845 ,  2.65555355, -1.0229343 ,  0.38653475]])

In [275]:

# acediendo ciertos datos
df['A']
df[1:3]
df[df.A > 0]

df.sort_values(by='B')

                   A         B         C         D
2020-01-04  0.714861 -0.995821  0.685179 -0.740736
2020-01-03  1.154601 -0.298438 -0.522687  1.401811
2020-01-02 -0.470731 -0.208458  1.895304  1.036726
2020-01-05 -0.952262  0.024284  0.211191 -2.044439
2020-01-01  0.797111  0.405615 -0.987697  0.569864
2020-01-06 -1.416184  2.655554 -1.022934  0.386535

In [276]:
# toda la estadistica descriptiva

df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.028767  0.263789  0.043059  0.101627
std    1.059105  1.258868  1.130510  1.279100
min   -1.416184 -0.995821 -1.022934 -2.044439
25%   -0.831879 -0.275943 -0.871444 -0.458918
50%    0.122065 -0.092087 -0.155748  0.478199
75%    0.776549  0.310282  0.566682  0.920010
max    1.154601  2.655554  1.895304  1.401811

## Comprender los datos con estadísticas descriptivas
Una vez que haya cargado sus datos en Python, debe poder entenderlos. Cuanto mejor pueda comprender sus datos, mejores y más precisos serán los modelos que puede construir.
El primer paso para comprender sus datos es utilizar estadísticas descriptivas. 

**Ejercicio**

- Realize un query sobre los datos que desea analizar con datos de precios de varios años
- Revise la distribución de sus datos con la función [describe()](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.describe.html#pandas.DataFrame.describe).
- Calcule la correlación por pares entre sus variables usando la función [corr ()](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.corr.html#pandas.DataFrame.corr) .

[documentación](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html)

In [287]:
import pandas as pd
import sqlite3
from IPython.display import display, HTML

# Read sqlite query results into a pandas DataFrame
con = sqlite3.connect("guia_fasecolda.sqlite")

#ESCRIBE LA CONSULTA DE LO QUE DESEAS ANALIZAR
#df = pd.read_sql_query('SELECT Marca,Referencia1,Cilindraje,Peso,"2015","2016","2017" FROM carros where Cilindraje<1500 AND Cilindraje>1200 AND "2015">0;', con)
#df = pd.read_sql_query('SELECT * FROM carros', con)
print("Query para traer la marca de carro AUDI y la clase a la cual pertenece de los años 2000 hasta 2017 de nacionalidad Colombiana")
print()
df = pd.read_sql_query('SELECT Marca,Clase FROM carros where Marca = "AUDI" AND (2000>0 OR 2001>0 OR'
                       ' 2002>0 OR 2003>0 OR 2004>0 OR 2005>0 OR 2006>0 OR 2007>0 OR 2008>0 OR 2009>0 OR 2010>0 OR 2011>0 OR'
                       ' 2012>0 OR 2013>0 OR 2014>0 OR 2015>0 OR 2016>0 OR 2017>0) order by clase;', con)


print("Total de memoria ram requerida ",df.memory_usage().sum())

#estadistica descriptiva
display(HTML(df.describe().to_html()))
#correlación entre las columnas
display(HTML(df.corr().to_html()))

con.close()

Query para traer la marca de carro AUDI y la clase a la cual pertenece de los años 2000 hasta 2017 de nacionalidad Colombiana

Total de memoria ram requerida  3744

Como notaste en el ejemplo anterior Pandas permite conectarse directamente a la base de datos, tambien permite leer datos en multiples formatos [documentation](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html) , por ejemplo si yo quiero cargar los datos originales de FASECOLDA

In [0]:
# Cargamos el archivo (solo en collaborative)
# from google.colab import files
# files.upload()

In [0]:

data = pd.read_csv('guia_fasecolda.csv')
print("Total de memoria ram requerida ",data.memory_usage().sum())


print(data.columns)



## Comprender los datos con visualización

Debes dedicar tiempo a comprender mejor tus datos. Una segunda forma de mejorar su comprensión de sus datos es mediante el uso de técnicas de visualización de datos . Usar la representación en Python para comprender los atributos por sí solos y sus interacciones. Ejemplos:
- Use la función hist () para crear un histograma de cada atributo.
- Use la función plot (kind = 'box') para crear diagramas de caja y cajas de cada atributo.
- Utilice la función  pandas.scatter_matrix() para crear gráficos de dispersión por pares de todos los atributos.

Es importante agregar```% inline matplotlib```  en la primera línea de su código si desea que la imagen esté incrustada en el *notebook* de Júpiter.


[pyplot](http://matplotlib.org/api/pyplot_api.html) es la mejor opción, claro que si trabajamos con Pandas, el tiene ya programada las graficas utlizando toda la información del dataset [ejemplo](https://pandas.pydata.org/pandas-docs/stable/10min.html#plotting)


**Ejercicio ** 

- Cargar el dataset de Fasecolda suministrado en csv

-  Comprenda sus datos usando la función `columns` para ver las filas
-  Utilize diferentes criterios para filtrar los datos.
-  utilize por lo menos tres funciones de pandas para describir los datos filtrados
-  Guarde los datos filtrados
-  Realize por lo menos tres graficas de los datos

[Link de descarga](https://drive.google.com/file/d/1mPnVLno8uLF1bD1EQbIRVUmxk1c1BVc4/view?usp=sharing)

In [0]:
# Load CSV using Pandas from URL
import pandas as pd
from IPython.display import display, HTML
data = pd.read_csv('guia_fasecolda.csv')

print(data.columns)

#Realiza diferentes filtros sobre los datos y describelos



# guarda los datos filtrados



display(HTML((data.head().to_html())))
#print(df[data['2015']>50000])

In [0]:

%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt

plt.figure()
data[['Cilindraje','Peso']].plot(kind = 'box',ylim=(-1000,10000))
plt.title('mi primera grafica')
plt.show()

## Conclusiones

De acuerdo a este análisis previo de los datos sobre la base de datos de FASECOLDA, que preguntas harias de análisis de datos que puedan generar valor.

Con que otra base de datos trabajarias para obtener valor de estos datos.

Utilize por lo menos dos análisis del curso de estadistica y/o de visualización de datos  para este problema.

Plantea una pregunta aprendizaje supervisado y otra de supervisado que pensarias genere valor sobre este dataset